// List of major cities and regencies across Indonesia
export const INDONESIA_CITIES = [
  "Banda Aceh",
  "Langsa",
  "Lhokseumawe",
  "Sabang",
  "Subulussalam",
  "Medan",
  "Binjai",
  "Gunungsitoli",
  "Padangsidimpuan",
  "Pematangsiantar",
  "Sibolga",
  "Tanjungbalai",
  "Tebing Tinggi",
  "Padang",
  "Bukittinggi",
  "Padang Panjang",
  "Pariaman",
  "Payakumbuh",
  "Sawahlunto",
  "Solok",
  "Pekanbaru",
  "Dumai",
  "Batam",
  "Tanjungpinang",
  "Jambi",
  "Sungai Penuh",
  "Palembang",
  "Lubuklinggau",
  "Pagar Alam",
  "Prabumulih",
  "Pangkalpinang",
  "Bengkulu",
  "Bandar Lampung",
  "Metro",
  "Jakarta Pusat",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Kepulauan Seribu",
  "Bogor",
  "Sukabumi",
  "Bandung",
  "Cirebon",
  "Bekasi",
  "Depok",
  "Cimahi",
  "Tasikmalaya",
  "Banjar",
  "Tangerang",
  "Tangerang Selatan",
  "Serang",
  "Cilegon",
  "Semarang",
  "Surakarta (Solo)",
  "Salatiga",
  "Magelang",
  "Pekalongan",
  "Tegal",
  "Purwokerto",
  "Kudus",
  "Cilacap",
  "Yogyakarta",
  "Sleman",
  "Bantul",
  "Surabaya",
  "Malang",
  "Madiun",
  "Kediri",
  "Mojokerto",
  "Blitar",
  "Pasuruan",
  "Probolinggo",
  "Batu",
  "Jember",
  "Banyuwangi",
  "Sidoarjo",
  "Gresik",
  "Denpasar",
  "Singaraja",
  "Badung",
  "Gianyar",
  "Mataram",
  "Bima",
  "Kupang",
  "Pontianak",
  "Singkawang",
  "Banjarbaru",
  "Banjarmasin",
  "Palangkaraya",
  "Balikpapan",
  "Bontang",
  "Samarinda",
  "Tarakan",
  "Nusantara (IKN)",
  "Manado",
  "Kotamobagu",
  "Tomohon",
  "Bitung",
  "Palu",
  "Makassar",
  "Palopo",
  "Parepare",
  "Kendari",
  "Baubau",
  "Gorontalo",
  "Mamuju",
  "Ambon",
  "Tual",
  "Ternate",
  "Tidore Kepulauan",
  "Jayapura",
  "Sorong",
  "Manokwari",
  "Merauke",
  "Nabire",
  "Wamena",
];
